### ISSUE TITLE
Large bundles with the generate-azure feature fail

### ISSUE THREAD

**Issue by mikeburgh** [microsoft/vscode-l10n#159]
If you try and translate a bundle with approx. 5000 characters it fails with the error: 

Error: Failed to translate: The maximum request size has been exceeded.

Looking at the code, if you reduce the character limit down to say 4000 here https://github.com/microsoft/vscode-l10n/blob/main/l10n-dev/src/translators/azure.ts#L44 

Then it works, however the resulting translations are then all mixed up.
With a small bundle, and no manual change to the character limit:
"Name": "Nome",

With a larger bundle, and a reduction of the character limit: 
 "Name": "Modificare la connessione",

**Comment by TylerLeonhardt** [comment]
Where is this string supposed to go, just so I know: `Modificare la connessione`

**Comment by TylerLeonhardt** [comment]
I'm thinking I'm just not handing large bundles well. I need to rework it. It's tough when Azure Translate only supports so much

**Comment by mikeburgh** [comment]
The incorrect string was from a different text key that was sent to translation. So it was a correct translation, just from a different key to the one it gets matched to in the output files

**Comment by TylerLeonhardt** [comment]
@mikeburgh this should be fixed in the [latest version of `@vscode/l10n-dev`](https://www.npmjs.com/package/@vscode/l10n-dev?activeTab=versions), 0.0.34. Can you give it a try and let me know how it goes?

**Comment by mikeburgh** [comment]
Thanks, on the road this week.. will test and confirm as soon as I get back

**Comment by TylerLeonhardt** [comment]
Tracking this as basic functionality as part of this https://github.com/microsoft/vscode-l10n/issues/154

**Comment by mikeburgh** [comment]
I upgraded to the latest version, but still having issues with request size: 

Error: Failed to translate: The server rejected the request because the client has exceeded request limits.
    at batchTranslate (/dev/node_modules/@vscode/l10n-dev/dist/cli.js:631:17)
